### ISSUE TITLE
TagLib Error

### ISSUE THREAD

**Issue by theonlynoddy** [erjiang/subs2srs#1]
Hi,

I am trying to install subs2srs on Ubuntu 20.04 and am getting the following errors when I run msbuild subs2srs.sln:

(ResolveAssemblyReferences target) -> 
  /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2101,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "policy.2.0.taglib-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

(CoreCompile target) -> 
  UtilsAudio.cs(26,7): error CS0246: The type or namespace name 'TagLib' could not be found (are you missing a using directive or an assembly reference?)

Using Mono version: 6.12.0.107

I have installed all of the prerequisites you listed, however, I have not been able to resolve this issue after a lot of searching. Any help you could offer for this issue would be much appreciated. Thanks for making the programme available, I'm keen to begin making anki cards using it!

**Comment by erjiang** [comment]
I have a `taglib-sharp.dll` that apparently isn't in the repo and I don't remember where I got it from either. Let me look into it...

**Comment by erjiang** [comment]
I should also warn you now that there are still some weird bugs when running it with Mono on Linux that I haven't spent time looking into and fixing, so hopefully you don't put high expectations on this.

**Comment by erjiang** [comment]
Can you try cloning and building https://github.com/mono/taglib-sharp/ ?

It should produce `taglib-sharp.dll` and `policy.2.0.taglib-sharp.dll`. Try copying the first one to the same directory as subs2srs.exe and if that doesn't work, copy the other one too. Let me how that goes and I'll update the Readme in this repo.

**Comment by erjiang** [comment]
Nevermind... I misunderstood the problem. (Sorry for all the messages, BTW.)

Building subs2srs requires the taglib external package. You can get it by running the following command in the cloned repo (same directory as `subs2srs.sln`):

    nuget install -OutputDirectory packages taglib

And then run `xbuild` and hopefully it builds fine.

**Comment by theonlynoddy** [comment]
Thanks for getting back to me so promptly and I apologise for the late response. This worked perfectly thanks for your help.

**Comment by vvlaw** [comment]
> 

Directory packages taglib
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'taglib' to '/home/vvlaw/tools/anki/subs2srs/subs2srs/packages'.
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/taglib/index.json
Unable to find package 'taglib'
