### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by CaioPython1** [erjiang/subs2srs#2]
sorry im not sure how to install it

**Comment by Unders0und** [comment]
I'm also clueless

**Comment by erjiang** [comment]
If you look in releases, you should find a zip file that contains a compiled version: https://github.com/erjiang/subs2srs/releases

Currently it's `subs2srs_v29.8.0.1.zip`

You can just extract the subs2srs directory somewhere and then run it with mono.

The other option is to compile it yourself (using `xbuild` or `msbuild`).
